### ISSUE TITLE
Should return with non-zero exit code when babel fails

### ISSUE THREAD

**Issue by nickolay** [runvnc/babel-changed#2]
I run babel-change from Atom via its [build package](https://atom.io/packages/build), using build-on-save feature. If there's an error with the build process, Atom pops up a panel with the console output.

If there's a syntax error preventing babel from compiling the source code, it prints the syntax error to the console and exits with a non-zero code. However babel-changed returns with 0 exit code, so the build process seems successful.

I fixed this locally by setting `exitCode` in the [exit handler](https://github.com/runvnc/babel-changed/blob/master/lib/index.js#L89):
```
 87 term.on('exit', function (code) {
 88   console.log('babel-changed detected exit code ', code);
 89   if (code === 0) cache.reconcile();
 90   process.exitCode = process.exitCode || code;
 91 });
```

**Comment by runvnc** [comment]
Ok thanks I will try to look into this today if I have time

On Mar 18, 2017 2:06 PM, "Nickolay Ponomarev" <notifications@github.com>
wrote:

I run babel-change from Atom via its build package
<https://atom.io/packages/build>, using build-on-save feature. If there's
an error with the build process, Atom pops up a panel with the console
output.

If there's a syntax error preventing babel from compiling the source code,
it prints the syntax error to the console and exits with a non-zero code.
However babel-changed returns with 0 exit code, so the build process seems
successull

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/runvnc/babel-changed/issues/2>, or mute the thread

**Comment by nickolay** [comment]
Great, thanks for the quick fix!
